.github/workflows/build-deploy.yml, saksstatistikk/pom.xml
Et skript som skal deploye kun moduler med endring
=> Byggeskript deploy

.github/workflows/build-deploy.yml, stonadsstatistikk/pom.xml, stonadsstatistikk/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt
Funksjonell id gjort om til optional
Fiks av github action jobb etter at støtten for set-env er fjernet og dermed ikke funket lenger
=> Gjør om funksjonell id til optional

stonadsstatistikk/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt
https://nav-it.slack.com/archives/C021DNF0RH9/p1624885712043100
=> Legg til behandlingårsak for rene satsendringsbehandlinger

saksstatistikk-ef/pom.xml, saksstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/ef/Saksstatistikk.kt, saksstatistikk-ef/src/test/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/ef/BehandlingDVHTest.kt, stonadsstatistikk-ef/pom.xml, stonadsstatistikk-ef/src/test/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVHTest.kt
Kompilering og eksekvering av testene mangler.
=> Lagt til kompilering og eksekvering av testmappe.

saksstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/ef/Saksstatistikk.kt, stonadsstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVH.kt
Typealias virker ikke fra javakode
=> Lagt til objekt for barnetilsyn

bisys/src/main/kotlin/no/nav/familie/eksterne/kontrakter/bisys/BarnetilsynBisysResponse.kt
Denne er ikke tatt i bruk ennå (@rinnan17 ?), så regner med det skal gå greit å gjøre dette uten "contract/expand". 
Jeg tar ansvar for å oppdatere familie-ef-sak så snart denne er på plass.
=> Vi sender mønedsbeløp, ikke "totalbeløp"

stonadsstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVH.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9060
=> Sletter utgiftstyper fra skolepenger då den ikke skal være med

stonadsstatistikk/README.md, stonadsstatistikk/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt, stonadsstatistikk/src/main/kotlin/no/nav/familie/eksterne/kontrakter/VedtakV2.kt
… støtte migrering hvor dette ikke blir fylt ut før årskontrollen
=> Stønadsstatistikk: støtte for å sette søkers aktivitet til null for å støtte migrering hvor dette ikke blir fylt ut før årskontrollen

stonadsstatistikk/README.md, stonadsstatistikk/src/main/kotlin/no/nav/familie/eksterne/kontrakter/VedtakV2.kt
Lagt til fagsaktype. Nullable for tilbakekompabilitet
=> Utvidelse stønadsstatistikk-kontrakt med fagsaktype for BA

bisys/src/main/kotlin/no/nav/familie/eksterne/kontrakter/bisys/BarnetilsynBisysResponse.kt
Bisys trenger ikke månedsbeløp, eller kilde (infotrygd, eller ef). Fjerner disse fra kontrakt.
=> Bisys bruker ikke kilde, eller månedsbeløp. Disse fjernes.

saksstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/ef/BehandlingDVH.kt, saksstatistikk-ef/src/test/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/ef/BehandlingDVHTest.kt, stonadsstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVH.kt, stonadsstatistikk-ef/src/test/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVHTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10431
=> EF årsak revurdering

arbeidsoppfolging/pom.xml, arbeidsoppfolging/src/main/kotlin/no/nav/familie/eksterne/kontrakter/arbeidsoppfolging/VedtakOvergangsstønadArbeidsoppfølging.kt, pom.xml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10630
https://nav-it.slack.com/archives/C032RLRDAPQ/p1675259451599639?thread_ts=1675172492.329289&cid=C032RLRDAPQ
=> Kontrakt for vedtaksperiode til arbeidsoppfølging

arbeidsoppfolging/pom.xml, bisys/pom.xml, pom.xml, saksstatistikk-ef/pom.xml, saksstatistikk-klage/pom.xml, saksstatistikk/pom.xml, skatteetaten/pom.xml, stonadsstatistikk-ef/pom.xml, stonadsstatistikk-ks/pom.xml, stonadsstatistikk/pom.xml
* Fjerner jaxb-java-time-adapterts, er ubrukt
* Flytter avhengighet til javax til dependencyManagement sånn at ikke alle er avhengig av det
Oppdaterer mvn i alle moduler for å trigge endring/bygge
=> Dependencies opprydding

stonadsstatistikk-ks/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12452
NAV-12452 Utvidet ekstern kontrakt for stønadsstatistikk for kontantstøtte
=> NAV-12452 Utvidet ekstern kontrakt for stønadsstatistikk for kontantstøtte

stonadsstatistikk-ks/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12452
Utvide ekstern kontrakt med nytt optional felt med antall timer i barnehage og ident + perioder
=> NAV-12452 Utvide ekstern kontrakt med nytt optional felt perioder

.github/workflows/deploy.yml
Fiks permissions i deploy workflow
=> Fiks permissions i deploy workflow

stonadsstatistikk-ef/src/main/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVH.kt
Ref [favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20614)
=> Skal legge inn eøsUnntak for datavarehus for EF

stonadsstatistikk-ks/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt
Denne må inn i felles eksterne kontrakter.
=> Legger til overgangsordning 2024 i kontrakter

stonadsstatistikk-ks/src/main/kotlin/no/nav/familie/eksterne/kontrakter/Vedtak.kt
Legger til ny behandlingsårsak PRAKSISENDRING_2024 for ks
=> Legg til ny behandlingsårsak PRAKSISENDRING_2024 for ks

.github/workflows/build.yml, .github/workflows/deploy.yml
Pinner workflows til sha. Måtte også oppgradere workflowsene til nyere versjoner
=> Pinner actions til sha

.github/dependabot.yml
Lagt til dependabot.yml. 
Selve configen er hentet fra familie-kontrakter
=> Lagt til dependabot-yml

pom.xml, saksstatistikk-ef/src/test/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/ef/BehandlingDVHTest.kt, saksstatistikk-klage/src/test/kotlin/no/nav/familie/eksterne/kontrakter/saksstatistikk/klage/BehandlingsstatistikkKlageTest.kt, stonadsstatistikk-ef/src/test/kotlin/no/nav/familie/eksterne/kontrakter/ef/BehandlingDVHTest.kt
Bumpet jackson og endret fra gammel konstruktør til ny funksjon
=> Bumper jackson
